### ISSUE TITLE
Support More Mixes

### ISSUE THREAD

**Issue by RyutoSetsujin** [city41/stepcharts#10]
I noticed there's quite a few games missing here... sorry if this sounds rude:

- Dancing Stage featuring TRUE KiSS DESTiNATiON
- DDR A20+
- DDR A3
- For some reason DDR Solo BASS MIX only has 3 out of the 6 NONSTOP MEGAMIX! songs...?

That's all, love the site :)

**Comment by city41** [comment]
I am adding all of those except for true kiss as zenius does not have it.

There's still some issues to work through, but you can see it here: https://stepcharts-4gyj56b2r-city41.vercel.app/

**Comment by city41** [comment]
ok this is done other than true kiss. If anyone has that, let me know and I'll add it. A3 is also missing a lot of banners, but that is what Zenius has so not much I can do about that.

**Comment by RyutoSetsujin** [comment]
I could get you TRUE KiSS DESTiNATiON
Oh, there's also Oha Suta DanceDanceRevolution if you wanna add that but that's like an entire spinoff on it's own I guess

Dancing Stage featuring TRUE KiSS DESTiNATiON: https://search.stepmaniaonline.net/pack/id/662

**Comment by RyutoSetsujin** [comment]
Also, seems like DCT is missing songs? https://search.stepmaniaonline.net/pack/id/661
