### ISSUE TITLE
Print layout isn't working anymore

### ISSUE THREAD

**Issue by Anonymous1157** [city41/stepcharts#12]
Hi! The multi-column print layout is currently broken. The page is laid out in single bars across the top of the page. I've reproduced this in desktop Firefox and Android Chromium, and a friend reproduced this in a very differently configured desktop Firefox.

I know you haven't had a chance to work on this project in over a year, so if there's anything I can do on my end to help narrow down the problem and make it easier to fix, let me know. I don't have a ton of web dev experience so I'm not sure I could fix it myself and send a patch...

![Example page with incorrect layout](https://user-images.githubusercontent.com/8900271/228102749-9c558524-1ee3-4af6-bfae-dc69603ad57c.png)

**Comment by city41** [comment]
Ah interesting. GitHub never alerted me to this issue. Sorry it's been so long. I'll try to carve out some time to look into this.

**Comment by city41** [comment]
This is now fixed. Turns out it was a dumb mistake I made. Sorry about that @Anonymous1157 . And sorry for being so late on this, like I said I am pretty sure github did not alert me to this issue despite having all notifications turned on.
