### ISSUE TITLE
Just saying thanks! ❤

### ISSUE THREAD

**Issue by noahm** [city41/stepcharts#8]
This is a really awesome project, and I appreciate it more each time I come back to read various bits of it. It's the only place I've found anybody publishing javascript code to parse stepfiles and that deserves major props!

I've been meaning to take your parser and extract it out to a separate package for a long time, and I finally did just that! It's over here:
https://www.npmjs.com/package/simfile-parser
https://github.com/noahm/simfile-parser

I already added some early SSC support on top of your code, and I'm using it to import ITG packs into my card draw app now: https://github.com/noahm/DDRCardDraw/pull/86

I'm sure I wouldn't have bothered to take it this far and publish my very first npm package without your high quality starting point. So, thanks for sharing and open sourcing it!

**Comment by city41** [comment]
Hey Noah, thanks glad you found the code useful. I remember the parses being pretty messy, :grimacing:, but they at least get the job done.

I remember you showing me DDR Draw ... a couple years ago on the SMX discord. Man time flies. It's looking awesome!

SSC support would be killer. I don't really know much about ITG, do ITG songs tend to use SSC?

**Comment by noahm** [comment]
Yes, ssc is just the format you get from the stepmania editor now (as of
5.1 I think?), so any songs charted in the past few years are all in that
format. It's close enough to sm that I didn't have to modify much at all
from your existing sm parser to get ssc working.

I want to eventually get the filesystem access abstracted out such that the
code can also run in the browser against the file access API there. The
dream would just be to get a card draw pack built on the fly by dragging
and dropping a stepmania pack directly into the browser.

**Comment by city41** [comment]
That would be really cool. I wanted to do something similar with stepcharts where people drag a step file or a zip and see the chart.

Yeah ssc is similar to sm, but there was something it added for new A20 songs. I don't remember what it was, I haven't worked on stepcharts in a long time now. Stepcharts skips Ace for Aces and Chaos Terror Tech-Mix in A20 due to them using ssc, and I believe only those two are sscs (the rest of A20 is sm) due to a new feature.

**Comment by noahm** [comment]
I don't know what Terror Tech does differently but I know Ace for Aces uses different BPMs and stops for each difficulty.(Basic is constant 100bpm, Standard is 100-200bpm, Expert is 100-200-400bpm) I haven't tested my ssc support against those new features but I think they will be easy to support without much more work. (Will also have to adjust the return types used to correctly model per-chart BPMs)

Would be happy to get contributions from you if you're interested, but I'll keep chipping away at it either way. I'm starting to plot out what else is worth doing in the short term here https://github.com/noahm/simfile-parser/projects/1

**Comment by city41** [comment]
Ah that's right, the bpm per difficulty differences. 

I'm definitely interested in helping. I probably won't be able to for the foreseeable future though, I'm currently quite swamped.

**Comment by noahm** [comment]
@city41 Just swinging by with an update: I did get around to adding decent support for parsing SSC files, and the latest version of the package also finally has preliminary support for [in-browser parsing of charts](https://github.com/noahm/simfile-parser#browser-support), and I'm using that to allow [drag-n-drop of a stepmania folder into the ddr.tools card draw app](https://github.com/noahm/DDRCardDraw/pull/238) to get card draw for any pack you might have locally.

I think it would be super neat to see your site eventually support something similar and get an instant, on-demand visualization of any chart just by dragging it into the page! :)

**Comment by city41** [comment]
@noahm nice! that's really cool. In the back of my mind I always wanted to allow people to just parse any chart they want. I'll see if I can squeeze this into the site at some point.
